stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: daystram/go-builder:1.16
  script:
    - go mod tidy
    - go build -a -o app .
  artifacts:
    paths:
      - app

test:
  stage: test
  image: daystram/go-builder:1.16
  dependencies:
    - build
  script:
    - go test ./tests/...

deploy:
  stage: deploy
  image: docker:19.03.12
  needs: ["test"]
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:19.03.12-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  when: manual
